name = "line-crm-worker"
main = "src/index.ts"
compatibility_date = "2024-12-01"
workers_dev = true
account_id = "37f8f88be4c099329e4647bda211bb9f"

# API_KEY is set via `wrangler secret put API_KEY`
# Do NOT hardcode secrets here

[vars]
WORKER_URL = "https://line-crm-worker.ryo-m-code.workers.dev"

[[d1_databases]]
binding = "DB"
database_name = "line-crm"
database_id = "734a6682-b446-4706-8348-556fded7a5b1"

[triggers]
crons = ["*/5 * * * *"]
